In [1]:
from text2vec import SentenceModel, cos_sim, semantic_search, BM25

c:\Python_tool\Anaconda\envs\torch\lib\site-packages\text2vec\utils\get_file.py:16: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm


In [7]:
from text2vec import SentenceModel, cos_sim, semantic_search

embedder = SentenceModel('shibing624/text2vec-base-chinese')

2023-05-23 11:53:13.789 | DEBUG    | text2vec.sentence_model:__init__:74 - Use device: cuda


In [14]:
corpus = [
    '花呗更改绑定银行卡',
    '我什么时候开通了花呗',
    'A man is eating food.',
    'A man is eating a piece of bread.',
    'The girl is carrying a baby.',
    'A man is riding a horse.',
    'A woman is playing violin.',
    'Two men pushed carts through the woods.',
    'A man is riding a white horse on an enclosed ground.',
    'A monkey is playing drums.',
    'A cheetah is running behind its prey.'
]
corpus_embeddings = embedder.encode(corpus,convert_to_tensor=True)

In [15]:
corpus_embeddings.shape

torch.Size([11, 768])

In [16]:
corpus_embeddings

tensor([[ 6.5362e-01, -7.6668e-02,  9.5962e-01,  ..., -6.0123e-01,
         -1.6794e-03,  2.1458e-01],
        [ 6.7082e-04, -4.6622e-01,  8.8384e-01,  ..., -6.5277e-01,
         -2.5951e-01, -4.0502e-01],
        [-6.9939e-02, -4.9385e-01,  3.7270e-01,  ...,  2.3021e-01,
         -6.6249e-01, -1.3724e-01],
        ...,
        [ 4.9589e-01, -1.0303e-01,  1.8840e-01,  ...,  1.1477e-01,
         -1.2948e+00,  9.4972e-01],
        [ 5.0110e-01, -4.1396e-01, -1.6148e-01,  ...,  3.5770e-03,
         -1.3249e+00,  3.8362e-01],
        [-1.5237e-02,  2.3721e-02,  4.1020e-01,  ..., -2.2118e-01,
         -9.9005e-01, -3.1756e-01]], device='cuda:0')

In [11]:
import torch
queries = [
    '如何更换花呗绑定银行卡',
    'A man is eating pasta.',
    'Someone in a gorilla costume is playing a set of drums.',
    'A cheetah chases prey on across a field.']

# Find the closest 5 sentences of the corpus for each query sentence based on cosine similarity
print('\nuse cos sim calc each query and corpus:')
top_k = min(5, len(corpus))
for query in queries:
    query_embedding = embedder.encode(query)

    # We use cosine-similarity and torch.topk to find the highest 5 scores
    cos_scores = cos_sim(query_embedding, corpus_embeddings)[0]
    top_results = torch.topk(cos_scores, k=top_k)

    print("\n\n======================\n\n")
    print("Query:", query)
    print("\nTop 5 most similar sentences in corpus:")

    for score, idx in zip(top_results[0], top_results[1]):
        print(corpus[idx], "(Score: {:.4f})".format(score))

print('#' * 42)
########  use semantic_search to perform cosine similarty + topk
print('\nuse semantic_search to perform cosine similarty + topk:')


use cos sim calc each query and corpus:




Query: 如何更换花呗绑定银行卡

Top 5 most similar sentences in corpus:
花呗更改绑定银行卡 (Score: 0.8551)
我什么时候开通了花呗 (Score: 0.7212)
A man is eating food. (Score: 0.3118)
A man is eating a piece of bread. (Score: 0.2992)
A monkey is playing drums. (Score: 0.2922)




Query: A man is eating pasta.

Top 5 most similar sentences in corpus:
A man is eating food. (Score: 0.7840)
A man is riding a white horse on an enclosed ground. (Score: 0.6906)
A man is eating a piece of bread. (Score: 0.6831)
A man is riding a horse. (Score: 0.6515)
Two men pushed carts through the woods. (Score: 0.5270)




Query: Someone in a gorilla costume is playing a set of drums.

Top 5 most similar sentences in corpus:
A monkey is playing drums. (Score: 0.6758)
A man is riding a white horse on an enclosed ground. (Score: 0.6351)
The girl is carrying a baby. (Score: 0.5438)
A man is riding a horse. (Score: 0.5002)
A man is eating a piece of bread. (Score: 0.4916)




Query: A cheetah chase

In [27]:
data = []
with open('./data/document_corpus.txt','r',encoding='utf-8') as f:
    for line in f:
        data.append(line.strip('\n'))

In [30]:
import pandas as pd
df = pd.DataFrame(data,columns=['title'])

title
0                         花呗更改绑定银行卡。
1                        我什么时候开通了花呗。
2              A man is eating food.
3  A man is eating a piece of bread.
4         A monkey is playing drums.

In [26]:
query = 'Win10怎么调整电脑分辨率'
ans = """ 在 Windows 10 中,可以通过以下步骤来调整分辨率:

1. 点击“开始”菜单,选择“设置”。
2. 点击“系统”选项卡。
3. 点击“显示”选项卡。
4. 在“屏幕分辨率”下拉菜单中,选择所需的分辨率。
5. 点击“确定”保存更改。

请注意,更改分辨率可能会影响图形质量和性能,因此在进行任何更改之前请先备份数据。"""
ans1 = """要调整电脑的分辨率,可以按照以下步骤进行操作:

1. 点击桌面或任务栏上的开始按钮,然后选择“设置”选项。
2. 在弹出的窗口中,选择“系统”选项卡。
3. 在左侧列表中,找到“显示器”选项,并双击打开它。
4. 在右侧窗口中,可以看到当前计算机使用的分辨率。如果想更改分辨率,请单击“更改分辨率”按钮。
5. 在弹出的对话框中,可以选择新分辨率,然后点击“确定”按钮保存更改。

请注意,更改分辨率可能会影响图形质量、字体大小和屏幕布局等。如果需要保留某些设置,请谨慎操作,确保在更改分辨率之前备份数据。"""
query_embed = embedder.encode(query)
ans_embed = embedder.encode(ans1)
cos_similarity = cos_sim(query_embed, ans_embed)[0]
print(cos_similarity)

tensor([0.5729])


In [ ]:
ac_doc = ''

In [23]:
embedder.encode(ans)

array([ 5.01444221e-01,  2.60543153e-02, -2.62759477e-01, -6.12628639e-01,
        5.08508682e-01, -9.66844618e-01,  4.15932298e-01,  1.32765621e-02,
       -1.45554054e+00,  1.89688057e-01,  5.41101575e-01, -1.86323494e-01,
        1.81932300e-01,  1.12610602e+00,  2.30607182e-01,  1.19988978e-01,
        1.44668877e-01,  6.62710547e-01, -3.46454680e-01,  4.05535400e-02,
       -1.98327184e-01, -3.91347229e-01,  6.09981790e-02,  9.04093385e-01,
        1.05874825e+00, -7.92602241e-01, -4.65949088e-01,  6.17189050e-01,
       -4.01372910e-01,  6.99428469e-02,  7.87648082e-01, -5.08369207e-01,
       -6.07964635e-01,  4.08847690e-01, -5.64885616e-01,  3.46235842e-01,
        4.68601227e-01,  6.11794949e-01, -1.95094645e-01,  5.58142066e-01,
       -3.73874791e-02,  7.36190915e-01, -9.88457441e-01, -4.45223272e-01,
       -3.92869860e-01,  4.62676048e-01,  3.27661693e-01,  2.18602777e-01,
       -4.12897766e-01,  1.02401882e-01,  1.11892089e-01,  7.08544016e+00,
        6.03835955e-02, -

In [12]:
for query in queries:
    query_embedding = embedder.encode(query)
    hits = semantic_search(query_embedding, corpus_embeddings, top_k=5)
    print("\n\n======================\n\n")
    print("Query:", query)
    print("\nTop 5 most similar sentences in corpus:")
    hits = hits[0]  # Get the hits for the first query
    for hit in hits:
        print(corpus[hit['corpus_id']], "(Score: {:.4f})".format(hit['score']))

print('#' * 42)
######## use bm25 to rank search score
print('\nuse bm25 to calc each score:')

search_sim = BM25(corpus=corpus)
for query in queries:
    print("\n\n======================\n\n")
    print("Query:", query)
    print("\nTop 5 most similar sentences in corpus:")
    for i in search_sim.get_scores(query, top_k=5):
        print(i[0], "(Score: {:.4f})".format(i[1]))





Query: 如何更换花呗绑定银行卡

Top 5 most similar sentences in corpus:
花呗更改绑定银行卡 (Score: 0.8551)
我什么时候开通了花呗 (Score: 0.7212)
A man is eating food. (Score: 0.3118)
A man is eating a piece of bread. (Score: 0.2992)
A monkey is playing drums. (Score: 0.2922)




Query: A man is eating pasta.

Top 5 most similar sentences in corpus:
A man is eating food. (Score: 0.7840)
A man is riding a white horse on an enclosed ground. (Score: 0.6906)
A man is eating a piece of bread. (Score: 0.6831)
A man is riding a horse. (Score: 0.6515)
Two men pushed carts through the woods. (Score: 0.5270)




Query: Someone in a gorilla costume is playing a set of drums.

Top 5 most similar sentences in corpus:
A monkey is playing drums. (Score: 0.6758)
A man is riding a white horse on an enclosed ground. (Score: 0.6351)
The girl is carrying a baby. (Score: 0.5438)
A man is riding a horse. (Score: 0.5002)
A man is eating a piece of bread. (Score: 0.4916)




Query: A cheetah chases prey on across a field.

Top 5 most sim

In [2]:
from text2vec import Similarity

sentences1 = ['如何更换花呗绑定银行卡',
              'The cat sits outside',
              'A man is playing guitar',
              'The new movie is awesome']

sentences2 = ['花呗更改绑定银行卡',
              'The dog plays in the garden',
              'A woman watches TV',
              'The new movie is so great']

sim_model = Similarity()
for i in range(len(sentences1)):
    for j in range(len(sentences2)):
        score = sim_model.get_score(sentences1[i], sentences2[j])
        print("{} \t\t {} \t\t Score: {:.4f}".format(sentences1[i], sentences2[j], score))

c:\Python_tool\Anaconda\envs\torch\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Opti7080\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

In [4]:
from sentence_transformers import SentenceTransformer
m = SentenceTransformer("shibing624/text2vec-base-chinese")

ModuleNotFoundError: No module named 'sentence_transformers'