In [1]:
import transformers

c:\Python_tool\Anaconda\envs\torch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [1]:
import torch

In [7]:
from IPython.display import display, Markdown, clear_output
def display_answer(query, history = []):
    # resp, history = get_knowledge_based_answer(query=query,
    #                                            vector_store=vector_store,
    #                                            chat_history=history)
    display(Markdown(query))
display_answer(query="ModelWhale 是什么")

ModelWhale 是什么

In [3]:
torch.cuda.is_available()

True

In [4]:
!nvidia-smi

Mon May 22 15:55:03 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.24       Driver Version: 528.24       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| 18%   32C    P8    14W / 215W |      0MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [1]:
from langchain.prompts import PromptTemplate

prompt = PromptTemplate(
    input_variables=["product"],
    template="What is a good name for a company that makes {product}?",
)

In [4]:
print(prompt.format(product="colorful socks"))

What is a good name for a company that makes colorful socks?


In [5]:
import os
os.path.isfile('./data/document_corpus.txt')

True

In [1]:
!ls

Untitled-1.ipynb
acquire_document.py
data
generate_summary.py
search_doc.py
text2vec.ipynb


In [5]:
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("shibing624/text2vec-base-chinese")

model = AutoModel.from_pretrained("shibing624/text2vec-base-chinese")

c:\Python_tool\Anaconda\envs\torch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Python_tool\Anaconda\envs\torch\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Opti7080\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this artic

In [6]:
def mean_pooling(model_output, attention_mask):
    token_embeddings = model_output[0]  # First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)


In [8]:
import torch
sentences = ['如何更换花呗绑定银行卡', '花呗更改绑定银行卡']
# Tokenize sentences
encoded_input = tokenizer(sentences, padding=True, truncation=True, return_tensors='pt')

# Compute token embeddings
with torch.no_grad():
    model_output = model(**encoded_input)
# Perform pooling. In this case, mean pooling.
sentence_embeddings = mean_pooling(model_output, encoded_input['attention_mask'])
print("Sentence embeddings:")
print(sentence_embeddings)

Sentence embeddings:
tensor([[-4.4399e-04, -2.9735e-01,  8.5790e-01,  ..., -5.2770e-01,
         -1.4316e-01, -1.0008e-01],
        [ 6.5362e-01, -7.6667e-02,  9.5962e-01,  ..., -6.0122e-01,
         -1.6797e-03,  2.1458e-01]])


In [7]:
from search_doc import embedder

[INFO]Loading Model


2023-05-23 17:00:46.318 | DEBUG    | text2vec.sentence_model:__init__:74 - Use device: cuda


In [8]:
embedder

In [2]:
import numba as nb

In [3]:
from math import sin

@nb.vectorize()
def nb_vec_sin(a):
    return sin(a)

In [38]:
a = np.random.randn(100000,768)
b = np.random.randn(1,768)

In [41]:
from text2vec import SentenceModel, cos_sim

In [48]:
import time
import numpy as np
import torch
a = np.random.randn(100000,768)
b = np.random.randn(1,768)
start_time = time.time()
c = cos_sim(a,b)
duration_1 = time.time()-start_time
start_time = time.time()
print(nb_vec_sin(a))
duration_2 = time.time()-start_time

a = torch.tensor(a).to('cuda')
b = torch.tensor(b).to('cuda')
s_time = time.time()
c_ = cos_sim(a,b)
duration_3 = time.time()-s_time

[[-0.25494302  0.35510558  0.65787946 ...  0.23777344  0.89951332
  -0.69283581]
 [-0.21394402 -0.02146462  0.73679789 ...  0.53819302  0.95069866
  -0.97943308]
 [ 0.73773584  0.5728007   0.56698357 ...  0.6696758  -0.91263461
  -0.87383107]
 ...
 [-0.53538724 -0.62236235  0.46455885 ... -0.72469746 -0.43196779
   0.1900131 ]
 [ 0.30064271 -0.95715459  0.9723309  ...  0.68655798  0.98785573
  -0.93550842]
 [-0.49164463 -0.22650817  0.64530563 ...  0.73041068  0.87517238
   0.74054606]]


In [51]:
c,c_

(tensor([[ 0.0379],
         [-0.0269],
         [ 0.0244],
         ...,
         [ 0.0316],
         [ 0.0020],
         [-0.0534]], dtype=torch.float64),
 tensor([[ 0.0379],
         [-0.0269],
         [ 0.0244],
         ...,
         [ 0.0316],
         [ 0.0020],
         [-0.0534]], device='cuda:0', dtype=torch.float64))

In [49]:
duration_1,duration_2,duration_3

(0.19809770584106445, 0.3446838855743408, 0.0020568370819091797)

In [13]:
%timeit(np.sin(a))

UsageError: Line magic function `%timeit(np.sin(a))` not found.


In [22]:
from numba import jit
@jit(nopython=True) 
def t():
    x = 0
    for i in np.arange(5000):
        x += i
    return x
%timeit t() 

1.91 µs ± 2.31 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [25]:
%timeit np.sin(a)
%timeit nb_vec_sin(a)

515 µs ± 768 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
232 µs ± 2.36 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [4]:
from transformers import AutoTokenizer,AutoModel
from argparse import Namespace
model_args = Namespace(do_mlm=None,pooler_type='cls', temp=0.05, mlp_only_train=False,init_embeddings_model=None)
tokenizer = AutoTokenizer.from_pretrained('silk-road/luotuo-bert')
model = AutoModel.from_pretrained('silk-road/luotuo-bert',trust_remote_code=True,model_args=model_args)

In [10]:
import torch
text_left = ['如何更换花呗绑定银行卡']

queries = [
    '如何更换花呗绑定银行卡',
    'A man is eating pasta.',
    'Someone in a gorilla costume is playing a set of drums.',
    'A cheetah chases prey on across a field.']

text_right = [
    '花呗更改绑定银行卡',
    '我什么时候开通了花呗',
    'A man is eating food.',
    'A man is eating a piece of bread.',
    'The girl is carrying a baby.',
    'A man is riding a horse.',
    'A woman is playing violin.',
    'Two men pushed carts through the woods.',
    'A man is riding a white horse on an enclosed ground.',
    'A monkey is playing drums.',
    'A cheetah is running behind its prey.'
]
text_left = queries
inputs = tokenizer(text_left, padding=True, truncation=True, return_tensors="pt")
with torch.no_grad():
    embeddings_left = model(**inputs, output_hidden_states=True, return_dict=True, sent_emb=True).pooler_output
inputs = tokenizer(text_right, padding=True, truncation=True, return_tensors="pt")
with torch.no_grad():
    embeddings_right = model(**inputs, output_hidden_states=True, return_dict=True, sent_emb=True).pooler_output
    
cos_sim_matrix = torch.matmul(embeddings_left, embeddings_right.t())
cos_sim_matrix /= torch.matmul(torch.norm(embeddings_left, dim=1, keepdim=True), torch.norm(embeddings_right, dim=1, keepdim=True).t())
tensor_cpu = cos_sim_matrix.cpu()

In [58]:
import os
def open_app(app_dir):
  os.startfile(app_dir)

In [59]:
!ls

Untitled-1.ipynb
__pycache__
data
generate_summary.py
inference.py
langchain-ChatGLM
main.py
map.py
operation
operation_idx.csv
renew_corpus.py
requirements.txt
search_doc.py
search_doc_faiss.py
search_doc_hf.py
stop_criterion.py
test_langchain.ipynb
text2vec.ipynb


In [2]:
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("GanymedeNil/text2vec-large-chinese")

model = AutoModel.from_pretrained("GanymedeNil/text2vec-large-chinese")

c:\Python_tool\Anaconda\envs\torch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
queries = [
    '如何更换花呗绑定银行卡',
    'A man is eating pasta.',
    'Someone in a gorilla costume is playing a set of drums.',
    'A cheetah chases prey on across a field.']

text_right = [
    '花呗更改绑定银行卡',
    '我什么时候开通了花呗',
    'A man is eating food.',
    'A man is eating a piece of bread.',
    'The girl is carrying a baby.',
    'A man is riding a horse.',
    'A woman is playing violin.',
    'Two men pushed carts through the woods.',
    'A man is riding a white horse on an enclosed ground.',
    'A monkey is playing drums.',
    'A cheetah is running behind its prey.'
]

In [1]:
import torch


In [2]:
torch.cuda.is_available()

True

In [3]:
torch.cuda_version

'11.8'

In [1]:
from peft import LoraConfig, get_peft_model, prepare_model_for_int8_training, TaskType

c:\Python_tool\Anaconda\envs\torch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm



===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
bin c:\Python_tool\Anaconda\envs\torch\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll c:\Python_tool\Anaconda\envs\torch\lib\site-packages\bitsandbytes libbitsandbytes_cuda116.dll
function 'cadam32bit_grad_fp32' not found
CUDA SETUP: Loading binary c:\Python_tool\Anaconda\envs\torch\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...


c:\Python_tool\Anaconda\envs\torch\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "


In [1]:
from huggingface_hub import snapshot_download
snapshot_download(repo_id="THUDM/chatglm-6b")

c:\Python_tool\Anaconda\envs\torch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Fetching 21 files: 100%|██████████| 21/21 [00:00<?, ?it/s]


'C:\\Users\\Opti7080\\.cache\\huggingface\\hub\\models--THUDM--chatglm-6b\\snapshots\\1d240ba371910e9282298d4592532d7f0f3e9f3e'

In [4]:
model = AutoModel.from_pretrained("THUDM/chatglm-6b-int4",trust_remote_code=True)

A new version of the following files was downloaded from https://huggingface.co/THUDM/chatglm-6b-int4:
- configuration_chatglm.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
A new version of the following files was downloaded from https://huggingface.co/THUDM/chatglm-6b-int4:
- quantization.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
A new version of the following files was downloaded from https://huggingface.co/THUDM/chatglm-6b-int4:
- modeling_chatglm.py
- quantization.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.


No compiled kernel found.
Compiling kernels : C:\Users\Opti7080\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\02a065cf2797029c036a02cac30f1da1a9bc49a3\quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\Opti7080\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\02a065cf2797029c036a02cac30f1da1a9bc49a3\quantization_kernels_parallel.c -shared -o C:\Users\Opti7080\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\02a065cf2797029c036a02cac30f1da1a9bc49a3\quantization_kernels_parallel.so
Compile default cpu kernel failed, using default cpu kernel code.
Compiling gcc -O3 -fPIC -std=c99 C:\Users\Opti7080\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\02a065cf2797029c036a02cac30f1da1a9bc49a3\quantization_kernels.c -shared -o C:\Users\Opti7080\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\02a065cf2797029c036a02cac30f1da1a9bc49a3\quantization_kern

ChatGLMForConditionalGeneration(
  (transformer): ChatGLMModel(
    (word_embeddings): Embedding(130528, 4096)
    (layers): ModuleList(
      (0-27): 28 x GLMBlock(
        (input_layernorm): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (attention): SelfAttention(
          (rotary_emb): RotaryEmbedding()
          (query_key_value): QuantizedLinear(in_features=4096, out_features=12288, bias=True)
          (dense): QuantizedLinear(in_features=4096, out_features=4096, bias=True)
        )
        (post_attention_layernorm): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
        (mlp): GLU(
          (dense_h_to_4h): QuantizedLinear(in_features=4096, out_features=16384, bias=True)
          (dense_4h_to_h): QuantizedLinear(in_features=16384, out_features=4096, bias=True)
        )
      )
    )
    (final_layernorm): LayerNorm((4096,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=4096, out_features=130528, bias=False)
)

In [14]:
from transformers import AutoTokenizer,AutoModel
import torch
model = AutoModel.from_pretrained("THUDM/chatglm-6b-int4", trust_remote_code=True).half().cuda()

tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b-int4", trust_remote_code=True)

c:\Python_tool\Anaconda\envs\torch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


No compiled kernel found.
Compiling kernels : C:\Users\Opti7080\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\02a065cf2797029c036a02cac30f1da1a9bc49a3\quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\Opti7080\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\02a065cf2797029c036a02cac30f1da1a9bc49a3\quantization_kernels_parallel.c -shared -o C:\Users\Opti7080\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\02a065cf2797029c036a02cac30f1da1a9bc49a3\quantization_kernels_parallel.so
Compile default cpu kernel failed, using default cpu kernel code.
Compiling gcc -O3 -fPIC -std=c99 C:\Users\Opti7080\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\02a065cf2797029c036a02cac30f1da1a9bc49a3\quantization_kernels.c -shared -o C:\Users\Opti7080\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\02a065cf2797029c036a02cac30f1da1a9bc49a3\quantization_kern

In [17]:
context = """本机物理MAC地址是：cc:d9:ac:d8:57:06,
本机电脑名是：DESKTOP-JHRQTGU.lenovo.com
本机IP是：10.176.130.235
本机硬盘序列号是：E823_8FA6_BF53_0001_001B_444A_4423_4BF2.
本机CPU序列号是：BFEBFBFF000A0655
本机主板序列号是：/41JYJ53/CNFCW0007K00LH/
本机bios序列号是：41JYJ53"""
inp = '我的MAC地址是什么'
input_text = f"""基于以下已知信息，简洁和专业的来回答用户的问题。
如果无法从中得到答案，请说 "根据已知信息无法回答该问题" 或 "没有提供足够的相关信息"，不允许在答案中添加编造成分，答案请使用中文。
##已知内容:
{context}
##问题:
{inp}
##回答："""

model.eval()
with torch.no_grad():
        
    input_ids = tokenizer.encode(input_text, return_tensors='pt').to('cuda')
    
    out = model.generate(
        input_ids=input_ids,
        max_length=300,
        temperature=0,
        top_p = 0.95,
        # repetition_penalty = 1.15,
        # stopping_criteria = StoppingCriteriaList([stop_criteria])
        # do_sample = True
    )
    answer = tokenizer.decode(out[0])
    print(answer)
    # item['infer_answer'] = answer
    # print(f"### {idx+1}.Answer:\n", item.get('output'), '\n\n')

基于以下已知信息,简洁和专业的来回答用户的问题。
如果无法从中得到答案,请说 "根据已知信息无法回答该问题" 或 "没有提供足够的相关信息",不允许在答案中添加编造成分,答案请使用中文。
##已知内容:
本机物理MAC地址是:cc:d9:ac:d8:57:06,
本机电脑名是:DESKTOP-JHRQTGU.lenovo.com
本机IP是:10.176.130.235
本机硬盘序列号是:E823_8FA6_BF53_0001_001B_444A_4423_4BF2.
本机CPU序列号是:BFEBFBFF000A0655
本机主板序列号是:/41JYJ53/CNFCW0007K00LH/
本机bios序列号是:41JYJ53
##问题:
我的MAC地址是什么
##回答: 根据已知信息,您的物理MAC地址是:cc:d9:ac:d8:57:06。


In [6]:
model.stream_chat()

<generator object ChatGLMForConditionalGeneration.stream_chat at 0x0000021269AA1E70>

In [1]:
re

'ai_user=pN1vaNEM/JFkEod5DPoEha|2023-06-08T02:24:16.518Z; ARRAffinity=4b55dda02c61fa6825af1a96193ff027e26cd4d1081dd1ee2ed88d88d93d93e9; ARRAffinitySameSite=4b55dda02c61fa6825af1a96193ff027e26cd4d1081dd1ee2ed88d88d93d93e9; .AspNetCore.Session=CfDJ8O%2ByR7SqPqxFlVz8eFNh6JFGsWDGqDT7Lzpzs4ImYU0jrnMFe6eWHIsbE52VYc8FRZV37J6ndDaxwjSxbvzE1fmeq53Mql%2B14DTKglIfKe9XpbajQ9UhJNbNo0v%2FYuluHZ5PoiEKJfG47olCOAp9n9QgGSclIv1Iak3PMKe9BclD; .AspNetCore.CookiesSSWeb=CfDJ8O-yR7SqPqxFlVz8eFNh6JEUTNyTeMBuOFEOcOPMwTcO-l0vrOFk0N9BKHtm_bRVY3W0u88P3I8fkCISyX_O7u15qf6PwF_D61PzBTgXJqHfBxQyHjf6rKXSu6YOduUWvsZG0qc4GNtZ7Jerm9yDkshdbEorp2nLmRpQ8obd91phvpKuqUxVl0avaXLOsBH8tOYY4FU7Zx6FtyNflVe6_-IkXRszZuU-9RLtwLSoKfMPjwMkfpUzUHECpB_puDrx4Hm6a6prhGkGKWifGk68HUZVUA9STh43cJklDVNwfwl6eBvUp8joU8TkaGoF1SHqN63HuOSpYv5gyjjS4Vd3Nls; ai_session=k434v/YYgul1PRSZB9GkaJ|1686191056621|1686192769861'

In [ ]:
input_text = """请你帮我根据以下instruction的要求提取出关键信息：
##instruction：要求格式为：
- 是否为电脑操作：
- 要求数字（未提及写未知）：
##input：
调整屏幕分辨率为1920*1080
##output:
"""
model.eval()
with torch.no_grad():
        
    input_ids = tokenizer.encode(input_text, return_tensors='pt').to('cuda')
    
    out = model.generate(
        input_ids=input_ids,
        max_length=200,
        temperature=0.3,
        top_p = 0.95,
        # repetition_penalty = 1.15,
        # stopping_criteria = StoppingCriteriaList([stop_criteria])
        # do_sample = True
    )
    answer = tokenizer.decode(out[0])
    print(answer)
    # item['infer_answer'] = answer
    # print(f"### {idx+1}.Answer:\n", item.get('output'), '\n\n')

In [68]:
input_text = """<用户>：请帮我打开微信
<ChatGLM-6B>:"""
model.eval()
with torch.no_grad():
        
    input_ids = tokenizer.encode(input_text, return_tensors='pt').to('cuda')
    
    out = model.generate(
        input_ids=input_ids,
        max_length=200,
        temperature=0.1,
        top_p = 0.95,
        # repetition_penalty = 1.15,
        # stopping_criteria = StoppingCriteriaList([stop_criteria])
        # do_sample = True
    )
    answer = tokenizer.decode(out[0])
    print(answer)
    # item['infer_answer'] = answer
    # print(f"### {idx+1}.Answer:\n", item.get('output'), '\n\n')

<用户>:请帮我打开微信
<ChatGLM-6B>: 很抱歉,作为一个语言模型,我无法直接打开微信应用程序。但是,您可以使用您的设备上的微信应用程序图标来打开它。如果该图标没有打开,您可以尝试在设备的设置中找到微信并打开它。


In [69]:
import json

if os.path.isfile('./operation/exe_location.json'):
    hash_map = json.loads('./operation/exe_location.json')

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [79]:
hash_map = {
    'QQMusic.exe':'C:/Program Files (x86)\Tencent\QQMusic',
    'msedge.exe':'C:/Program Files (x86)\Microsoft\Edge\Application'
    }


In [80]:
with open('./operation/exe_location.json', 'w') as write_f:
	json.dump(hash_map, write_f, indent=4, ensure_ascii=False)


In [81]:
with open('./operation/exe_location.json','r') as load_f:
    hash_map = json.load(load_f)
    print(hash_map)
    print(type(load_dict))


{'QQMusic.exe': 'C:/Program Files (x86)\\Tencent\\QQMusic', 'msedge.exe': 'C:/Program Files (x86)\\Microsoft\\Edge\\Application'}
<class 'dict'>


In [5]:
import screen_brightness_control as sbc
sbc.get_brightness()[0]

10

In [32]:
sbc.get_brightness()[0]

100

In [6]:
sbc.set_brightness(100)

In [7]:
model.device

device(type='cuda', index=0)

In [1]:
from peft import PeftModel,LoraConfig,get_peft_model
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, AutoConfig,AutoModel


model = AutoModel.from_pretrained("THUDM/chatglm-6b-int4", load_in_8bit=True, trust_remote_code=True, device_map='auto')
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm-6b-int4", trust_remote_code=True)

model.supports_gradient_checkpointing = True
model.gradient_checkpointing_enable()
model.enable_input_require_grads()
# model.lm_head = CastOutputToFloat(model.lm_head)
model.config.use_cache = False  # silence the warnings. Please re-enable for inference!
peft_config = LoraConfig(
    task_type='CAUSAL_LM', inference_mode=True,
    r=8,
    lora_alpha=32, lora_dropout=0.1,
)
# model = PeftModel.from_pretrained(model, "./tzh_model/medical_glm")
model = get_peft_model(model, peft_config)
model.is_parallelizable = True
model.model_parallel = True



c:\Python_tool\Anaconda\envs\torch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm



===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
bin c:\Python_tool\Anaconda\envs\torch\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll c:\Python_tool\Anaconda\envs\torch\lib\site-packages\bitsandbytes libbitsandbytes_cuda116.dll
function 'cadam32bit_grad_fp32' not found
CUDA SETUP: Loading binary c:\Python_tool\Anaconda\envs\torch\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...


c:\Python_tool\Anaconda\envs\torch\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "


OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like THUDM/chatglm-6b-int4 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

In [1]:
from operation.operation import Operation3
inps = {'inputs':input('Input: ')}
test = Operation3(**inps)

{'QQMusic.exe': 'C:/Program Files (x86)\\Tencent\\QQMusic'}


In [2]:
test.fit()

c:\Python_tool\Anaconda\envs\torch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
usage: Matching Task [-h] [--document-corpus DOCUMENT_CORPUS]
                     [--new-embed NEW_EMBED] [--document-embed DOCUMENT_EMBED]
                     [--k K] [--device DEVICE] [--model-name MODEL_NAME]
                     [--index_location INDEX_LOCATION]
Matching Task: error: unrecognized arguments: --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"6374c16d-bbe1-4643-92c1-507310150e28" --shell=9002 --transport="tcp" --iopub=9004 --f=c:\Users\Opti7080\AppData\Roaming\jupyter\runtime\kernel-v2-21952m58WaRixzUOk.json


SystemExit: 2

c:\Python_tool\Anaconda\envs\torch\lib\site-packages\IPython\core\interactiveshell.py:3516: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [1]:
import bitsandbytes

In [17]:
!ls

01.wav
02.wav
03.wav
Untitled-1.ipynb
__pycache__
data
exe_location.json
generate_summary.py
inference.py
langchain-ChatGLM
main.py
map.py
operation
operation_idx.csv
play.py
recognition.py
record.py
renew_corpus.py
requirements.txt
result.wav
search_doc.py
search_doc_faiss.py
search_doc_hf.py
stop_criterion.py
synthesis.py
test_langchain.ipynb
test_thred.py
text2vec.ipynb
zh.wav


In [3]:
import torch
torch.__version__

'2.0.1+cu118'

In [5]:
import torch
inputs = tokenizer(queries, padding=True, truncation=True, return_tensors="pt")
with torch.no_grad():
    embeddings_que = model(**inputs)
    embeddings_ans = model(**tokenizer(text_right, padding=True, truncation=True, return_tensors="pt"))

In [6]:
embeddings_que.last_hidden_state.shape,embeddings_que.pooler_output.shape

(torch.Size([4, 22, 1024]), torch.Size([4, 1024]))

In [7]:
embeddings_que.last_hidden_state[:,0].numpy()

array([[-0.19582476, -0.22542259,  0.5878763 , ...,  0.51889557,
        -0.97035754,  0.72239023],
       [-0.36700755,  0.29916915,  0.31173083, ...,  1.2112145 ,
         0.05619805,  0.93658125],
       [-0.9832982 , -0.7832372 , -1.5102569 , ...,  1.4223759 ,
        -1.4264588 ,  0.75840706],
       [-1.4391133 ,  0.4106356 , -0.12989327, ..., -0.03974489,
        -1.0173508 , -0.79071593]], dtype=float32)

In [1]:

import faiss

In [8]:
from transformers import AutoModel,AutoTokenizer
import torch
device = 'cuda:0'
tokenizer = AutoTokenizer.from_pretrained("GanymedeNil/text2vec-large-chinese")
model = AutoModel.from_pretrained("GanymedeNil/text2vec-large-chinese").to(device)

def l2_normalization(data):
    if data.ndim == 1:
        return data / np.linalg.norm(data).reshape(-1,1)
    else:
        return data/np.linalg.norm(data,axis=1).reshape(-1,1)
def cls_pooling(model_output,return_tensors=False):
    if not return_tensors:
        return l2_normalization(model_output.last_hidden_state[:,0].cpu().numpy())
    else:
        return l2_normalization(model_output.last_hidden_state[:,0])
    


c:\Python_tool\Anaconda\envs\torch\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [26]:
corpus = []
with open('../data/document_corpus.txt','r',encoding='utf-8') as f:
    for line in f:
        corpus.append(line.strip('\n'))
def mean_pooling(model_output, attention_mask, return_tensors=False):
    token_embeddings = model_output[0]  # First element of model_output contains all token embeddings
    input_mask_expanded = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    output = torch.sum(token_embeddings * input_mask_expanded, 1) / torch.clamp(input_mask_expanded.sum(1), min=1e-9)
    if not return_tensors:
        return output.cpu().numpy()
    else:
        return output

In [27]:

import numpy as np
model.eval()
input_data = tokenizer(corpus, padding=True, return_tensors="pt")
with torch.no_grad():
    corpus_embeddings = model(**input_data.to(device))
# corpus_embeddings = cls_pooling(corpus_embeddings)
corpus_embeddings = mean_pooling(corpus_embeddings,attention_mask=input_data['attention_mask'])
corpus_embeddings = l2_normalization(corpus_embeddings)

In [28]:
query =  '帮我记录一下明天上午十点要买菜'
input_data = tokenizer(query, padding=True, return_tensors="pt")  
model.eval()     
with torch.no_grad():
    query_embeddings = model(**input_data.to('cuda'))
    # query_embeddings = cls_pooling(query_embeddings)
    query_embeddings = mean_pooling(query_embeddings,attention_mask=input_data['attention_mask'])
    feature_search = l2_normalization(query_embeddings)  

In [29]:
corpus_embeddings@feature_search.T

array([[0.23497748],
       [0.2247234 ],
       [0.27397212],
       [0.2500224 ]], dtype=float32)

In [30]:
corpus

['调节屏幕亮度', '询问显存占用', '进行事件提醒', '打开某个软件']

In [8]:
import faiss
import numpy as np
features = l2_normalization(np.load("./data/document_embed.npy"))
dim = features.shape[1]
index_ip = faiss.IndexFlatIP(dim)
index_ip.add(features)
print(index_ip.ntotal) 

6


In [99]:
np.array((corpus))

array(['调节屏幕亮度', '调整屏幕分辨率', '打开软件', '询问显存', '询问GPU占用', '创建记事本备忘录'],
      dtype='<U8')

In [80]:
aux_index = faiss.IndexIDMap(index_ip) 

RuntimeError: Error in __cdecl faiss::IndexIDMapTemplate<struct faiss::Index>::IndexIDMapTemplate(struct faiss::Index *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\IndexIDMap.cpp:32: Error: 'index->ntotal == 0' failed: index must be empty on input

In [42]:
from search_doc_faiss import faiss_corpus
torch.cuda.empty_cache()
corpus = faiss_corpus()
corpus.fit()

[INFO]Loading Model
[INFO]Creating Document Embeddings
['调节屏幕亮度', '询问显存占用', '进行事件提醒', '打开软件', '询问GPU占用']
[INFO]Finishing Saving Indexing


In [4]:
corpus.corpus

['调节屏幕亮度', '询问显存占用', '创建备忘录进行事项提醒', '打开软件', '询问GPU占用']

In [20]:
index.reconstruct(0),index_ip.reconstruct(0)

(array([-0.01932951,  0.0241784 ,  0.02330983, ...,  0.02350627,
        -0.03408533,  0.0198594 ], dtype=float32),
 array([-0.04149882,  0.04571409, -0.02394647, ..., -0.03245361,
         0.04087428, -0.01606109], dtype=float32))

In [77]:
l2_normalization_1(features[1,:]),l2_normalization(features[1,:])

(array([[-0.03973337,  0.00838783,  0.01816207, ..., -0.00785893,
         -0.05274578,  0.00404025]], dtype=float32),
 array([-0.03973337,  0.00838783,  0.01816207, ..., -0.00785893,
        -0.05274578,  0.00404025], dtype=float32))

In [15]:
features.shape

(6, 1024)

In [12]:
import faiss
import numpy as np

query = '提醒我明天十点抢电影票'
index = faiss.read_index('./data/test.index')
with torch.no_grad():
    query_embeddings = model(**tokenizer(query, padding=True, return_tensors="pt").to(device))
query_embeddings = cls_pooling(query_embeddings)
feature_search = query_embeddings
# 检索最相似的topK个特征
topK = 5
D, I = index.search(feature_search, topK)
# 返回的D表示相似度（或者距离）, I表示检索的topK个特征id（索引）


In [52]:
query = '帮我记录一下明天十点提醒帮我买菜'
corpus_1 = """进行事件提醒"""
corpus_2 = """调节屏幕亮度"""

with torch.no_grad():
    query_embeddings = model(**tokenizer(query, padding=True, return_tensors="pt").to(device))
    feature_search = model(**tokenizer(corpus_1, padding=True, return_tensors="pt").to(device))
    feature_search_2 = model(**tokenizer(corpus_2, padding=True, return_tensors="pt").to(device))
feature_search = cls_pooling(feature_search)
query_embeddings = cls_pooling(query_embeddings)
feature_search_2 = cls_pooling(feature_search_2)

In [53]:
query_embeddings@feature_search.T,query_embeddings@feature_search_2.T

(array([[0.42430413]], dtype=float32), array([[0.3600703]], dtype=float32))

In [17]:
query_embeddings.shape,feature_search.shape

((1, 1024), (1, 1024))

In [7]:
D, I

(array([[0.38714254, 0.37287977, 0.3670662 , 0.3359719 , 0.30211502]],
       dtype=float32),
 array([[0, 2, 3, 1, 4]], dtype=int64))

In [8]:
corpus.corpus

['调节屏幕亮度', '询问显存占用', '创建备忘录进行事项提醒', '打开软件', '询问GPU占用']

In [27]:
D, I

(array([[0.38714254, 0.3670662 , 0.36462313, 0.3359719 , 0.30211502]],
       dtype=float32),
 array([[0, 3, 2, 1, 4]], dtype=int64))

In [28]:
# 保存索引
faiss.write_index(index_ip, './data/test.index')

# 读取索引
index = faiss.read_index('./data/test.index')


NameError: name 'index_ip' is not defined

In [22]:
import torch
query = '提醒我明天十点抢电影票'
with torch.no_grad():
    query_embeddings = model(**tokenizer(query, padding=True, return_tensors="pt").to('cuda'))
query_embeddings = cls_pooling(query_embeddings)
feature_search = query_embeddings
# 检索最相似的topK个特征
topK = 5
D, I = index.search(feature_search, topK)
# 返回的D表示相似度（或者距离）, I表示检索的topK个特征id（索引）

NameError: name 'cls_pooling' is not defined

In [47]:
index

<faiss.swigfaiss.IndexFlat; proxy of <Swig Object of type 'faiss::IndexFlat *' at 0x000001A3B59EF900> >

In [48]:
D, I

(array([[0.7988719 , 0.56085855, 0.4258615 , 0.41730604, 0.3314243 ]],
       dtype=float32),
 array([[1, 5, 3, 0, 2]], dtype=int64))

In [49]:
corpus.corpus

['调节屏幕亮度', '询问显存占用', '创建记事本备忘录', '调整屏幕分辨率', '打开软件', '询问GPU占用']

In [34]:
def normalization(data):
    _range = np.max(data) - np.min(data)
    return (data - np.min(data)) / _range
 
 
def standardization(data):
    mu = np.mean(data, axis=1)
    sigma = np.std(data, axis=1)
    return (data - mu) / sigma



np.sum(l2_normalization(query_embeddings))

-0.38731813

In [28]:
query_embeddings.shape

(1, 1024)

In [35]:
np.linalg.norm(l2_normalization(query_embeddings))

1.0

In [21]:
query_embeddings

array([[-0.19582501, -0.2254237 ,  0.5878755 , ...,  0.51889545,
        -0.9703573 ,  0.7223894 ]], dtype=float32)

In [20]:
D,I

(array([[835.5797 , 564.0149 , 397.68317, 339.4082 , 246.25342]],
       dtype=float32),
 array([[0, 1, 4, 3, 2]], dtype=int64))

In [ ]:
index_ids = faiss.IndexFlatIP(2048)
index_ids = faiss.IndexIDMap(index_ids)

# 添加特征，并指定id，注意添加的id类型为int64
ids = 20
feature_ids = np.random.random((1, 2048)).astype('float32')
index_ids.add_with_ids(feature_ids, np.array((ids,)).astype('int64'))


In [4]:
index_ip

<faiss.swigfaiss.IndexFlatIP; proxy of <Swig Object of type 'faiss::IndexFlatIP *' at 0x000001D6C6EFF570> >

In [8]:
from text2vec import cos_sim
cos_similarity = cos_sim(embeddings_que.last_hidden_state[:,0],embeddings_ans.last_hidden_state[:,0])
print(cos_similarity)

tensor([[0.9465, 0.6756, 0.2798, 0.3837, 0.4044, 0.2968, 0.2742, 0.3308, 0.3206,
         0.4471, 0.4081],
        [0.3055, 0.2763, 0.7725, 0.6567, 0.3291, 0.7498, 0.2632, 0.4862, 0.5845,
         0.4109, 0.4650],
        [0.3777, 0.3504, 0.3729, 0.5051, 0.5157, 0.4793, 0.5053, 0.4642, 0.5326,
         0.6118, 0.5007],
        [0.3411, 0.3380, 0.3204, 0.4363, 0.4000, 0.4164, 0.3400, 0.4188, 0.5530,
         0.3807, 0.5776]])


In [41]:
cos_similarity.argmax(dim=1)

tensor([ 0,  2,  9, 10])

In [13]:
tensor_cpu.argmax(dim=1)

tensor([ 0,  2,  9, 10])

In [22]:
from text2vec import cos_sim

In [14]:
tensor_cpu.shape

torch.Size([4, 11])

In [15]:
tensor_cpu

tensor([[0.9719, 0.8737, 0.7577, 0.7623, 0.7647, 0.7870, 0.7640, 0.7554, 0.7812,
         0.7794, 0.7791],
        [0.7596, 0.8073, 0.9713, 0.9700, 0.8659, 0.9233, 0.8840, 0.8633, 0.9166,
         0.8967, 0.9084],
        [0.7571, 0.7907, 0.8844, 0.8987, 0.8838, 0.9239, 0.9227, 0.8731, 0.9319,
         0.9432, 0.9264],
        [0.7539, 0.7718, 0.8788, 0.9024, 0.8693, 0.9033, 0.8655, 0.8638, 0.9149,
         0.8890, 0.9299]])

In [23]:
import screen_brightness_control as sbc

In [29]:
sbc.get_brightness()

[100]

In [35]:
sbc.set_brightness(90)

In [37]:
import os
os.system('nvidia-smi')

0

In [38]:
import pynvml
pynvml.nvmlInit()
handle = pynvml.nvmlDeviceGetHandleByIndex(0)
info = pynvml.nvmlDeviceGetMemoryInfo(handle)
print(f"Total memory: {info.total/1024**2} MB")
print(f"Free memory: {info.free/1024**2} MB")
print(f"Used memory: {info.used/1024**2} MB")

Total memory: 8192.0 MB
Free memory: 6604.09375 MB
Used memory: 1587.90625 MB


In [41]:
# from operation.screen_brightness import operation
# opt = operation(50)
# opt.fit()
from operation.display_graphic import operation
opt = operation()
opt.fit()

Total memory: 8192.00 MB
Free memory: 6604.09 MB
Used memory: 1587.91 MB


In [1]:
from operation import operation



In [2]:
selected_idx = 0
inp = {"brightness":100}
opt = eval(f"operation.Operation{selected_idx}")(**inp)

In [3]:
opt.fit()

'已调至100%'

In [43]:
def time_suffix():
    return time.strftime("%Y%m%d%H%M%S", time.localtime(time.time()))

In [45]:
import time 
time_suffix()

'20230529144958'

In [47]:
os.path.join('LenoMate',time_suffix(),'.txt')

'LenoMate\\20230529145105\\.txt'

In [48]:
summary='love'

In [51]:
'LenoMate_'+summary+'_'+time_suffix()+'.txt'

'LenoMate_love_20230529145339.txt'

In [55]:
def test_args_kwargs(arg1, arg2, arg3,arg4=5):
    print("arg1:", arg1)
    print("arg2:", arg2)
    print("arg3:", arg3)

In [56]:
kwargs = {"arg3": 3, "arg2": "two", "arg1": 5}
test_args_kwargs(**kwargs)

#result
arg1: 5
arg2: 'two'
arg3: 3

arg1: 5
arg2: two
arg3: 3


In [61]:
import os
import time
default_path = os.path.join(os.path.expanduser("~"), "Desktop")
class operation():
    def __init__(self,inputs,path=default_path,summary='notebook'):
        self.path = path
        self.inputs = inputs
        self.summary = summary
    def fit(self):
        file_name = 'LenoMate_'+self.summary+'_'+time_suffix()+'.txt'
        file_name = os.path.join(default_path,file_name)
        with open(file_name,'w',encoding='utf-8') as f:
            f.write(self.inputs)
        f.close()
inp = {'inputs':'s','summary':'love'}
tst = operation(**inp)

In [62]:
tst.summary

'love'

In [57]:
import re

string=""" instruction:
- 任务: 调整屏幕亮度
- 要求数字: 10
output:
- 将屏幕亮度调低到10"""
re.findall(r"\d+\.?\d*",string)

['10', '10']

In [1]:
import threading
import queue
import numpy as np

# 模拟加载和运行模型的函数
def load_and_run_model(input_queue):
    # 模型加载过程，可以根据实际情况进行编写
    print("模型加载中...")
    # 模型加载完成
    print("模型加载完成")

    while True:
        try:
            # 从输入队列中获取输入数据
            input_data = input_queue.get()
            # 在这里进行模型处理
            # 模型处理逻辑...
            # 将输入数据转换为numpy数组
            input_array = eval(input_data)
            # 运行模型，这里我们简单地将输入数据乘以2
            output_array = input_array * 2
            # 将结果转换为字符串
            output_data = str(output_array)

            # 处理完成后，可以将结果返回给主线程，或者进行其他操作
            print("模型输出：", output_data)
        except KeyboardInterrupt:
            break

# 创建一个输入队列
input_queue = queue.Queue()

# 创建一个线程，用于加载和运行模型
model_thread = threading.Thread(target=load_and_run_model, args=(input_queue,))
# 设置线程为后台线程，使程序可以退出
model_thread.daemon = True
# 启动线程
model_thread.start()

while True:
    # 接收用户输入
    input_data = input("请输入数据（输入'exit'退出）：")
    if input_data == "exit":
        break
    # 将输入数据放入输入队列
    input_queue.put(input_data)

# 退出程序时，清空输入队列并等待模型线程结束
input_queue.join()


模型加载中...
模型加载完成
模型输出： 2
模型输出： 4
模型输出： 6
模型输出： 8
模型输出： 10
模型输出： 12


Exception in thread Thread-3 (load_and_run_model):
Traceback (most recent call last):
  File "c:\Python_tool\Anaconda\envs\torch\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "c:\Python_tool\Anaconda\envs\torch\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Opti7080\AppData\Local\Temp\ipykernel_8504\1912693514.py", line 19, in load_and_run_model
  File "<string>", line 0
    
SyntaxError: invalid syntax


In [5]:
import re
answer = """
数字:未知
"""
try:
    num = int(re.findall(r"\d+\.?\d*",answer.split('数字:')[1])[0])
except:
    num = answer.split('数字:')[1]

In [1]:
num

NameError: name 'num' is not defined

In [3]:
import os
os.system('ffmpeg -y -i data/voice1.wav -ac 1 -ar 16000 data/voice.wav')

1

In [1]:
import socket 


In [2]:
import uuid

def get_mac_address():
    mac=uuid.UUID(int = uuid.getnode()).hex[-12:]
    return ":".join([mac[e:e+2] for e in range(0,11,2)])

print(get_mac_address())

cc:d9:ac:d8:57:06


In [8]:
import socket
def get_computer_name_ip():
    #获取本机电脑名
    name = socket.getfqdn(socket.gethostname())
    #获取本机ip
    addr = socket.gethostbyname(socket.gethostname())
    return name,addr

myname,myaddr = get_computer_name_ip()
print('电脑名:',myname)
print('ip地址:',myaddr)


电脑名: DESKTOP-JHRQTGU.lenovo.com
ip地址: 10.176.130.235


In [9]:
import wmi

c = wmi.WMI()

# # 硬盘序列号
for physical_disk in c.Win32_DiskDrive():
    print("硬盘序列号", physical_disk.SerialNumber)

# CPU序列号
for cpu in c.Win32_Processor():
    print("CPU序列号", cpu.ProcessorId.strip())

# 主板序列号
for board_id in c.Win32_BaseBoard():
    print("主板序列号", board_id.SerialNumber)

# mac地址
for mac in c.Win32_NetworkAdapter():
    print("mac地址", mac.MACAddress)

# bios序列号
for bios_id in c.Win32_BIOS():
    print("bios序列号", bios_id.SerialNumber.strip())



硬盘序列号 E823_8FA6_BF53_0001_001B_444A_4423_4BF2.
CPU序列号 BFEBFBFF000A0655
主板序列号 /41JYJ53/CNFCW0007K00LH/
mac地址 None
mac地址 CC:D9:AC:D8:57:02
mac地址 A4:BB:6D:CE:5A:8C
mac地址 CC:D9:AC:D8:57:06
mac地址 CC:D9:AC:D8:57:03
mac地址 None
mac地址 None
mac地址 None
mac地址 None
mac地址 None
mac地址 BC:9B:20:52:41:53
mac地址 BA:7F:20:52:41:53
mac地址 BA:8A:20:52:41:53
mac地址 CE:D9:AC:D8:57:02
bios序列号 41JYJ53


In [13]:
c.Win32_BaseBoard()[0].SerialNumber

'/41JYJ53/CNFCW0007K00LH/'

In [11]:
c.Win32_BIOS()[0].SerialNumber.strip()

'41JYJ53'

In [6]:
socket.getfqdn(socket.gethostname())

'DESKTOP-JHRQTGU.lenovo.com'

In [7]:
socket.gethostbyname(socket.gethostname())

'10.176.130.235'